name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Persist npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Persist Eleventy .cache
        uses: actions/cache@v3
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache

      - run: npm install

      - name: Build with Eleventy
        run: npm run build-ghpages
        env: 
          ELEVENTY_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

      - name: Set status to success
        uses: actions/create-status@v2
        with:
          context: 'workflow-status'
          description: 'Deployed to GitHub Pages 🎉'
          state: 'success'  # You can change this to 'failure' for error notifications
          target_url: 'https://flohgro-dev.github.io/11ty_test/'  # Optional, link to more information (e.g., build logs)

      - name: Notify on success
        run: |
          echo "Workflow completed successfully!"