name: ⚙️ Build Eleventy Site

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: 🛠️ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 🗄️ Cache npm Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: 💾 Persist Eleventy .cache
        uses: actions/cache@v3
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache

      - run: npm install

      - name: 🏗️ Build Eleventy Site
        run: npm run build-ghpages
        env: 
          ELEVENTY_ENV: production

      